### ISSUE TITLE
MacOS lldb support

### ISSUE THREAD

**Issue by mahaloz** [mahaloz/decomp2dbg#59]
## TODO
- [ ] add `decompiler` command with Python
- [ ] stop-event hook
- [ ] define variables per stack var/reg var
- [ ] create a MachO and add symbols

## Useful Info
- https://lldb.llvm.org/use/python-reference.html (command and stop-event)
